app_http:
     port: 8080 #api server port

dbagent_grpc:
  host: "calculator-dbagent"
  port: 8085

expression:
  maxLength:  50 #max allowed length of expression
  hungTimeout: 300 #in sec if subtask will not evaluate after taken by agent in that period, her evaluation started and agent field will be cleared to allow another agent to take it
  agentDownTimeout: 1 #in minutes how long allowed not to send heartbeat
  hungCheckPeriod: 1 #in sec how often we will check free of agents tasks
  agentDownCheckPeriod: 1 #how often we will check agent heartbeat

auth:
  access_token_ttl: 60m
  refresh_token_ttl: 720h

ampq_queue_server:
  url: "amqp://guest:guest@message-broker:5672/"
ampq_queue_struct:
  work_exchange:
    name: "CalculatorWorkExchange"
  retry_exchange:
    name: "CalculatorRetryExchange"
  consumer:
    exchange_name:  "CalculatorWorkExchange"
    query_name: "CalculatorWorkQueue"
  queries: [
    {name: "CalculatorWorkQueue", dlx: "CalculatorRetryExchange", ttl: -1},
    {name: "CalculatorRetryQueue", dlx: "CalculatorWorkExchange", ttl: 20000},
  ]
  binds:  [
    {query_name: "CalculatorWorkQueue", exchange_name: "CalculatorWorkExchange"},
    {query_name: "CalculatorRetryQueue", exchange_name: "CalculatorRetryExchange"},
  ]