// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.5
// source: dbagent/internal/api/grpcservice/writergrpc/writer.proto

package writergrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentName string `protobuf:"bytes,1,opt,name=agentName,proto3" json:"agentName,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type StartEvalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeId  int64  `protobuf:"varint,1,opt,name=seId,proto3" json:"seId,omitempty"`
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *StartEvalRequest) Reset() {
	*x = StartEvalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEvalRequest) ProtoMessage() {}

func (x *StartEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEvalRequest.ProtoReflect.Descriptor instead.
func (*StartEvalRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{1}
}

func (x *StartEvalRequest) GetSeId() int64 {
	if x != nil {
		return x.SeId
	}
	return 0
}

func (x *StartEvalRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type StartEvalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StartEvalResponse) Reset() {
	*x = StartEvalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEvalResponse) ProtoMessage() {}

func (x *StartEvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEvalResponse.ProtoReflect.Descriptor instead.
func (*StartEvalResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{2}
}

func (x *StartEvalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopEvalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeId   int64   `protobuf:"varint,1,opt,name=seId,proto3" json:"seId,omitempty"`
	Result float64 `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	Error  string  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *StopEvalRequest) Reset() {
	*x = StopEvalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEvalRequest) ProtoMessage() {}

func (x *StopEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEvalRequest.ProtoReflect.Descriptor instead.
func (*StopEvalRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{3}
}

func (x *StopEvalRequest) GetSeId() int64 {
	if x != nil {
		return x.SeId
	}
	return 0
}

func (x *StopEvalRequest) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *StopEvalRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_dbagent_internal_api_grpcservice_writergrpc_writer_proto protoreflect.FileDescriptor

var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc = []byte{
	0x0a, 0x38, 0x64, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x30, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x3c, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22,
	0x2d, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x53,
	0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x32, 0xcd, 0x01, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x12, 0x18, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x40, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61,
	0x6c, 0x12, 0x18, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76,
	0x61, 0x6c, 0x12, 0x17, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x56, 0x61, 0x64, 0x69, 0x6d, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x2f, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x64, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescOnce sync.Once
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData = file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc
)

func file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP() []byte {
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescOnce.Do(func() {
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData = protoimpl.X.CompressGZIP(file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData)
	})
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData
}

var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_goTypes = []interface{}{
	(*HeartbeatRequest)(nil),  // 0: writer.HeartbeatRequest
	(*StartEvalRequest)(nil),  // 1: writer.StartEvalRequest
	(*StartEvalResponse)(nil), // 2: writer.StartEvalResponse
	(*StopEvalRequest)(nil),   // 3: writer.StopEvalRequest
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_depIdxs = []int32{
	0, // 0: writer.WriterService.Heartbeat:input_type -> writer.HeartbeatRequest
	1, // 1: writer.WriterService.StartEval:input_type -> writer.StartEvalRequest
	3, // 2: writer.WriterService.StopEval:input_type -> writer.StopEvalRequest
	4, // 3: writer.WriterService.Heartbeat:output_type -> google.protobuf.Empty
	2, // 4: writer.WriterService.StartEval:output_type -> writer.StartEvalResponse
	4, // 5: writer.WriterService.StopEval:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_init() }
func file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_init() {
	if File_dbagent_internal_api_grpcservice_writergrpc_writer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEvalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEvalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopEvalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_goTypes,
		DependencyIndexes: file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_depIdxs,
		MessageInfos:      file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes,
	}.Build()
	File_dbagent_internal_api_grpcservice_writergrpc_writer_proto = out.File
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc = nil
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_goTypes = nil
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_depIdxs = nil
}
