// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.5
// source: dbagent/internal/api/grpcservice/writergrpc/writer.proto

package writergrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64   `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ReqUid         string  `protobuf:"bytes,3,opt,name=reqUid,proto3" json:"reqUid,omitempty"`
	Value          string  `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Result         float64 `protobuf:"fixed64,5,opt,name=result,proto3" json:"result,omitempty"`
	State          string  `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Error          string  `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt      int64   `protobuf:"varint,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	EvalStartedAt  int64   `protobuf:"varint,9,opt,name=evalStartedAt,proto3" json:"evalStartedAt,omitempty"`
	EvalFinishedAt int64   `protobuf:"varint,10,opt,name=evalFinishedAt,proto3" json:"evalFinishedAt,omitempty"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{0}
}

func (x *Expression) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Expression) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Expression) GetReqUid() string {
	if x != nil {
		return x.ReqUid
	}
	return ""
}

func (x *Expression) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Expression) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Expression) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Expression) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Expression) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Expression) GetEvalStartedAt() int64 {
	if x != nil {
		return x.EvalStartedAt
	}
	return 0
}

func (x *Expression) GetEvalFinishedAt() int64 {
	if x != nil {
		return x.EvalFinishedAt
	}
	return 0
}

type SubExpression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ExpressionId      int64   `protobuf:"varint,2,opt,name=expressionId,proto3" json:"expressionId,omitempty"`
	Val1              float64 `protobuf:"fixed64,3,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2              float64 `protobuf:"fixed64,4,opt,name=val2,proto3" json:"val2,omitempty"`
	SubExpressionId1  int64   `protobuf:"varint,5,opt,name=subExpressionId1,proto3" json:"subExpressionId1,omitempty"`
	SubExpressionId2  int64   `protobuf:"varint,6,opt,name=subExpressionId2,proto3" json:"subExpressionId2,omitempty"`
	Operation         string  `protobuf:"bytes,7,opt,name=operation,proto3" json:"operation,omitempty"`
	OperationDuration uint32  `protobuf:"varint,8,opt,name=operationDuration,proto3" json:"operationDuration,omitempty"`
	IsLast            bool    `protobuf:"varint,9,opt,name=isLast,proto3" json:"isLast,omitempty"`
}

func (x *SubExpression) Reset() {
	*x = SubExpression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubExpression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubExpression) ProtoMessage() {}

func (x *SubExpression) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubExpression.ProtoReflect.Descriptor instead.
func (*SubExpression) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{1}
}

func (x *SubExpression) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubExpression) GetExpressionId() int64 {
	if x != nil {
		return x.ExpressionId
	}
	return 0
}

func (x *SubExpression) GetVal1() float64 {
	if x != nil {
		return x.Val1
	}
	return 0
}

func (x *SubExpression) GetVal2() float64 {
	if x != nil {
		return x.Val2
	}
	return 0
}

func (x *SubExpression) GetSubExpressionId1() int64 {
	if x != nil {
		return x.SubExpressionId1
	}
	return 0
}

func (x *SubExpression) GetSubExpressionId2() int64 {
	if x != nil {
		return x.SubExpressionId2
	}
	return 0
}

func (x *SubExpression) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *SubExpression) GetOperationDuration() uint32 {
	if x != nil {
		return x.OperationDuration
	}
	return 0
}

func (x *SubExpression) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentName string `protobuf:"bytes,1,opt,name=agentName,proto3" json:"agentName,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type StartEvalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeId  int64  `protobuf:"varint,1,opt,name=seId,proto3" json:"seId,omitempty"`
	Agent string `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *StartEvalRequest) Reset() {
	*x = StartEvalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEvalRequest) ProtoMessage() {}

func (x *StartEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEvalRequest.ProtoReflect.Descriptor instead.
func (*StartEvalRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{3}
}

func (x *StartEvalRequest) GetSeId() int64 {
	if x != nil {
		return x.SeId
	}
	return 0
}

func (x *StartEvalRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

type StartEvalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *StartEvalResponse) Reset() {
	*x = StartEvalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartEvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEvalResponse) ProtoMessage() {}

func (x *StartEvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEvalResponse.ProtoReflect.Descriptor instead.
func (*StartEvalResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{4}
}

func (x *StartEvalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StopEvalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeId   int64   `protobuf:"varint,1,opt,name=seId,proto3" json:"seId,omitempty"`
	Result float64 `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	Error  string  `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *StopEvalRequest) Reset() {
	*x = StopEvalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopEvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEvalRequest) ProtoMessage() {}

func (x *StopEvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEvalRequest.ProtoReflect.Descriptor instead.
func (*StopEvalRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{5}
}

func (x *StopEvalRequest) GetSeId() int64 {
	if x != nil {
		return x.SeId
	}
	return 0
}

func (x *StopEvalRequest) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *StopEvalRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadySubExpressionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EId            int64  `protobuf:"varint,1,opt,name=eId,proto3" json:"eId,omitempty"`
	SkipTimeoutSec uint32 `protobuf:"varint,2,opt,name=skipTimeoutSec,proto3" json:"skipTimeoutSec,omitempty"`
}

func (x *ReadySubExpressionsRequest) Reset() {
	*x = ReadySubExpressionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadySubExpressionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadySubExpressionsRequest) ProtoMessage() {}

func (x *ReadySubExpressionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadySubExpressionsRequest.ProtoReflect.Descriptor instead.
func (*ReadySubExpressionsRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{6}
}

func (x *ReadySubExpressionsRequest) GetEId() int64 {
	if x != nil {
		return x.EId
	}
	return 0
}

func (x *ReadySubExpressionsRequest) GetSkipTimeoutSec() uint32 {
	if x != nil {
		return x.SkipTimeoutSec
	}
	return 0
}

type ReadySubExpressionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubExpressions []*SubExpression `protobuf:"bytes,1,rep,name=SubExpressions,proto3" json:"SubExpressions,omitempty"`
}

func (x *ReadySubExpressionsResponse) Reset() {
	*x = ReadySubExpressionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadySubExpressionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadySubExpressionsResponse) ProtoMessage() {}

func (x *ReadySubExpressionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadySubExpressionsResponse.ProtoReflect.Descriptor instead.
func (*ReadySubExpressionsResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{7}
}

func (x *ReadySubExpressionsResponse) GetSubExpressions() []*SubExpression {
	if x != nil {
		return x.SubExpressions
	}
	return nil
}

type ExpressionByReqUidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ReqUid string `protobuf:"bytes,2,opt,name=reqUid,proto3" json:"reqUid,omitempty"`
}

func (x *ExpressionByReqUidRequest) Reset() {
	*x = ExpressionByReqUidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpressionByReqUidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionByReqUidRequest) ProtoMessage() {}

func (x *ExpressionByReqUidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionByReqUidRequest.ProtoReflect.Descriptor instead.
func (*ExpressionByReqUidRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{8}
}

func (x *ExpressionByReqUidRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ExpressionByReqUidRequest) GetReqUid() string {
	if x != nil {
		return x.ReqUid
	}
	return ""
}

type CreateExpressionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	E *Expression `protobuf:"bytes,1,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *CreateExpressionRequest) Reset() {
	*x = CreateExpressionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpressionRequest) ProtoMessage() {}

func (x *CreateExpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpressionRequest.ProtoReflect.Descriptor instead.
func (*CreateExpressionRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{9}
}

func (x *CreateExpressionRequest) GetE() *Expression {
	if x != nil {
		return x.E
	}
	return nil
}

type CreateExpressionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateExpressionResponse) Reset() {
	*x = CreateExpressionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExpressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpressionResponse) ProtoMessage() {}

func (x *CreateExpressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpressionResponse.ProtoReflect.Descriptor instead.
func (*CreateExpressionResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{10}
}

func (x *CreateExpressionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateSubExpressionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Se *SubExpression `protobuf:"bytes,1,opt,name=se,proto3" json:"se,omitempty"`
}

func (x *CreateSubExpressionRequest) Reset() {
	*x = CreateSubExpressionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubExpressionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubExpressionRequest) ProtoMessage() {}

func (x *CreateSubExpressionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubExpressionRequest.ProtoReflect.Descriptor instead.
func (*CreateSubExpressionRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSubExpressionRequest) GetSe() *SubExpression {
	if x != nil {
		return x.Se
	}
	return nil
}

type CreateSubExpressionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSubExpressionResponse) Reset() {
	*x = CreateSubExpressionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSubExpressionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubExpressionResponse) ProtoMessage() {}

func (x *CreateSubExpressionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubExpressionResponse.ProtoReflect.Descriptor instead.
func (*CreateSubExpressionResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{12}
}

func (x *CreateSubExpressionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetExpressionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetExpressionsRequest) Reset() {
	*x = GetExpressionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExpressionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpressionsRequest) ProtoMessage() {}

func (x *GetExpressionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpressionsRequest.ProtoReflect.Descriptor instead.
func (*GetExpressionsRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{13}
}

func (x *GetExpressionsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetExpressionsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expressions []*Expression `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
}

func (x *GetExpressionsResponse) Reset() {
	*x = GetExpressionsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetExpressionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpressionsResponse) ProtoMessage() {}

func (x *GetExpressionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpressionsResponse.ProtoReflect.Descriptor instead.
func (*GetExpressionsResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{14}
}

func (x *GetExpressionsResponse) GetExpressions() []*Expression {
	if x != nil {
		return x.Expressions
	}
	return nil
}

type Agent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	LastHbAt  int64  `protobuf:"varint,3,opt,name=lastHbAt,proto3" json:"lastHbAt,omitempty"`
}

func (x *Agent) Reset() {
	*x = Agent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{15}
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Agent) GetLastHbAt() int64 {
	if x != nil {
		return x.LastHbAt
	}
	return 0
}

type GetAgentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Agents []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
}

func (x *GetAgentsResponse) Reset() {
	*x = GetAgentsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentsResponse) ProtoMessage() {}

func (x *GetAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentsResponse.ProtoReflect.Descriptor instead.
func (*GetAgentsResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{16}
}

func (x *GetAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type OperationDuration struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Duration  uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	CreatedAt int64  `protobuf:"varint,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt int64  `protobuf:"varint,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *OperationDuration) Reset() {
	*x = OperationDuration{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OperationDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationDuration) ProtoMessage() {}

func (x *OperationDuration) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationDuration.ProtoReflect.Descriptor instead.
func (*OperationDuration) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{17}
}

func (x *OperationDuration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OperationDuration) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *OperationDuration) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OperationDuration) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateOperDurRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Duration uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *CreateOperDurRequest) Reset() {
	*x = CreateOperDurRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOperDurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperDurRequest) ProtoMessage() {}

func (x *CreateOperDurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperDurRequest.ProtoReflect.Descriptor instead.
func (*CreateOperDurRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{18}
}

func (x *CreateOperDurRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOperDurRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type GetOperDurResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationDurations []*OperationDuration `protobuf:"bytes,1,rep,name=operationDurations,proto3" json:"operationDurations,omitempty"`
}

func (x *GetOperDurResponse) Reset() {
	*x = GetOperDurResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOperDurResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperDurResponse) ProtoMessage() {}

func (x *GetOperDurResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperDurResponse.ProtoReflect.Descriptor instead.
func (*GetOperDurResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{19}
}

func (x *GetOperDurResponse) GetOperationDurations() []*OperationDuration {
	if x != nil {
		return x.OperationDurations
	}
	return nil
}

type SkipAgentSubExpressionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentName string `protobuf:"bytes,1,opt,name=agentName,proto3" json:"agentName,omitempty"`
}

func (x *SkipAgentSubExpressionsRequest) Reset() {
	*x = SkipAgentSubExpressionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkipAgentSubExpressionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipAgentSubExpressionsRequest) ProtoMessage() {}

func (x *SkipAgentSubExpressionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipAgentSubExpressionsRequest.ProtoReflect.Descriptor instead.
func (*SkipAgentSubExpressionsRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{20}
}

func (x *SkipAgentSubExpressionsRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Token     string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt int64  `protobuf:"varint,4,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{21}
}

func (x *Token) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Token) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Token) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Token) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CreateTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token     string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt int64  `protobuf:"varint,3,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTokenRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateTokenRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{23}
}

func (x *CreateTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenValue string `protobuf:"bytes,1,opt,name=tokenValue,proto3" json:"tokenValue,omitempty"`
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{24}
}

func (x *GetTokenRequest) GetTokenValue() string {
	if x != nil {
		return x.TokenValue
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *Token `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{25}
}

func (x *GetTokenResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Login        string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password     string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Admin        bool   `protobuf:"varint,4,opt,name=admin,proto3" json:"admin,omitempty"`
	RegisteredAt int64  `protobuf:"varint,5,opt,name=registeredAt,proto3" json:"registeredAt,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{26}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *User) GetRegisteredAt() int64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Admin    bool   `protobuf:"varint,3,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{27}
}

func (x *CreateUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{28}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByCredRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *GetUserByCredRequest) Reset() {
	*x = GetUserByCredRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByCredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByCredRequest) ProtoMessage() {}

func (x *GetUserByCredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByCredRequest.ProtoReflect.Descriptor instead.
func (*GetUserByCredRequest) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{29}
}

func (x *GetUserByCredRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserByCredRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetUserByCredResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserByCredResponse) Reset() {
	*x = GetUserByCredResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByCredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByCredResponse) ProtoMessage() {}

func (x *GetUserByCredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByCredResponse.ProtoReflect.Descriptor instead.
func (*GetUserByCredResponse) Descriptor() ([]byte, []int) {
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP(), []int{30}
}

func (x *GetUserByCredResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_dbagent_internal_api_grpcservice_writergrpc_writer_proto protoreflect.FileDescriptor

var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc = []byte{
	0x0a, 0x38, 0x64, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x92, 0x02, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x55, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x71, 0x55, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x76, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x65,
	0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x65, 0x76, 0x61, 0x6c, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x76, 0x61, 0x6c, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68,
	0x65, 0x64, 0x41, 0x74, 0x22, 0xa7, 0x02, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x65, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61,
	0x6c, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x76, 0x61,
	0x6c, 0x32, 0x12, 0x2a, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x73, 0x75,
	0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x31, 0x12, 0x2a,
	0x0a, 0x10, 0x73, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x32, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x73, 0x75, 0x62, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x11, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73, 0x4c, 0x61, 0x73, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x61, 0x73, 0x74, 0x22, 0x30,
	0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x3c, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x73, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x2d,
	0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x53, 0x0a,
	0x0f, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x56, 0x0a, 0x1a, 0x52, 0x65, 0x61, 0x64, 0x79, 0x53, 0x75, 0x62, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x6b, 0x69, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x53, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x73, 0x6b, 0x69, 0x70,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x22, 0x5c, 0x0a, 0x1b, 0x52, 0x65,
	0x61, 0x64, 0x79, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0e, 0x53, 0x75, 0x62,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x62, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4b, 0x0a, 0x19, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79, 0x52, 0x65, 0x71, 0x55, 0x69, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x71, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x71, 0x55, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x01, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x01, 0x65, 0x22, 0x2a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43,
	0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x02,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x02, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x75, 0x62,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a,
	0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x55, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x62, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x62, 0x41, 0x74, 0x22, 0x3a, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x06, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x06,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x7f, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x70, 0x65, 0x72, 0x44, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x5f, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x44, 0x75, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x12, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x12, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x3e, 0x0a, 0x1e, 0x53, 0x6b, 0x69, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x63, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0x60, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x22, 0x3a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x31, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x82, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x5b, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x22, 0x36, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x39, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79,
	0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x32, 0xd9,
	0x09, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3d, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x18, 0x2e,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x40, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x12, 0x18, 0x2e, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3b, 0x0a, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76, 0x61, 0x6c, 0x12, 0x17, 0x2e,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x45, 0x76, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x61,
	0x0a, 0x16, 0x47, 0x65, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x79, 0x53, 0x75, 0x62, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x79, 0x52, 0x65, 0x71, 0x55, 0x69, 0x64, 0x12, 0x21, 0x2e, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x79,
	0x52, 0x65, 0x71, 0x55, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x55, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x22, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1d, 0x2e, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19,
	0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x15, 0x53, 0x61, 0x76,
	0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x44, 0x75, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x72, 0x44, 0x75, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x17, 0x53, 0x6b, 0x69, 0x70, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x26, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x6b, 0x69, 0x70, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x43, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19,
	0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x77, 0x72, 0x69, 0x74,
	0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x42, 0x79, 0x43, 0x72, 0x65, 0x64, 0x12, 0x1c, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x43, 0x72, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x17, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x61, 0x64, 0x69, 0x6d, 0x47, 0x6f,
	0x73, 0x73, 0x69, 0x70, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x64, 0x62, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x72, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescOnce sync.Once
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData = file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc
)

func file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescGZIP() []byte {
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescOnce.Do(func() {
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData = protoimpl.X.CompressGZIP(file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData)
	})
	return file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDescData
}

var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_goTypes = []interface{}{
	(*Expression)(nil),                     // 0: writer.Expression
	(*SubExpression)(nil),                  // 1: writer.SubExpression
	(*HeartbeatRequest)(nil),               // 2: writer.HeartbeatRequest
	(*StartEvalRequest)(nil),               // 3: writer.StartEvalRequest
	(*StartEvalResponse)(nil),              // 4: writer.StartEvalResponse
	(*StopEvalRequest)(nil),                // 5: writer.StopEvalRequest
	(*ReadySubExpressionsRequest)(nil),     // 6: writer.ReadySubExpressionsRequest
	(*ReadySubExpressionsResponse)(nil),    // 7: writer.ReadySubExpressionsResponse
	(*ExpressionByReqUidRequest)(nil),      // 8: writer.ExpressionByReqUidRequest
	(*CreateExpressionRequest)(nil),        // 9: writer.CreateExpressionRequest
	(*CreateExpressionResponse)(nil),       // 10: writer.CreateExpressionResponse
	(*CreateSubExpressionRequest)(nil),     // 11: writer.CreateSubExpressionRequest
	(*CreateSubExpressionResponse)(nil),    // 12: writer.CreateSubExpressionResponse
	(*GetExpressionsRequest)(nil),          // 13: writer.GetExpressionsRequest
	(*GetExpressionsResponse)(nil),         // 14: writer.GetExpressionsResponse
	(*Agent)(nil),                          // 15: writer.Agent
	(*GetAgentsResponse)(nil),              // 16: writer.GetAgentsResponse
	(*OperationDuration)(nil),              // 17: writer.OperationDuration
	(*CreateOperDurRequest)(nil),           // 18: writer.CreateOperDurRequest
	(*GetOperDurResponse)(nil),             // 19: writer.GetOperDurResponse
	(*SkipAgentSubExpressionsRequest)(nil), // 20: writer.SkipAgentSubExpressionsRequest
	(*Token)(nil),                          // 21: writer.Token
	(*CreateTokenRequest)(nil),             // 22: writer.CreateTokenRequest
	(*CreateTokenResponse)(nil),            // 23: writer.CreateTokenResponse
	(*GetTokenRequest)(nil),                // 24: writer.GetTokenRequest
	(*GetTokenResponse)(nil),               // 25: writer.GetTokenResponse
	(*User)(nil),                           // 26: writer.User
	(*CreateUserRequest)(nil),              // 27: writer.CreateUserRequest
	(*CreateUserResponse)(nil),             // 28: writer.CreateUserResponse
	(*GetUserByCredRequest)(nil),           // 29: writer.GetUserByCredRequest
	(*GetUserByCredResponse)(nil),          // 30: writer.GetUserByCredResponse
	(*emptypb.Empty)(nil),                  // 31: google.protobuf.Empty
}
var file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_depIdxs = []int32{
	1,  // 0: writer.ReadySubExpressionsResponse.SubExpressions:type_name -> writer.SubExpression
	0,  // 1: writer.CreateExpressionRequest.e:type_name -> writer.Expression
	1,  // 2: writer.CreateSubExpressionRequest.se:type_name -> writer.SubExpression
	0,  // 3: writer.GetExpressionsResponse.expressions:type_name -> writer.Expression
	15, // 4: writer.GetAgentsResponse.agents:type_name -> writer.Agent
	17, // 5: writer.GetOperDurResponse.operationDurations:type_name -> writer.OperationDuration
	21, // 6: writer.CreateTokenResponse.token:type_name -> writer.Token
	21, // 7: writer.GetTokenResponse.token:type_name -> writer.Token
	26, // 8: writer.CreateUserResponse.user:type_name -> writer.User
	26, // 9: writer.GetUserByCredResponse.user:type_name -> writer.User
	2,  // 10: writer.WriterService.Heartbeat:input_type -> writer.HeartbeatRequest
	3,  // 11: writer.WriterService.StartEval:input_type -> writer.StartEvalRequest
	5,  // 12: writer.WriterService.StopEval:input_type -> writer.StopEvalRequest
	6,  // 13: writer.WriterService.GetReadySubExpressions:input_type -> writer.ReadySubExpressionsRequest
	8,  // 14: writer.WriterService.GetExpressionByReqUid:input_type -> writer.ExpressionByReqUidRequest
	9,  // 15: writer.WriterService.CreateExpression:input_type -> writer.CreateExpressionRequest
	11, // 16: writer.WriterService.CreateSubExpression:input_type -> writer.CreateSubExpressionRequest
	13, // 17: writer.WriterService.GetExpressions:input_type -> writer.GetExpressionsRequest
	31, // 18: writer.WriterService.GetAgents:input_type -> google.protobuf.Empty
	18, // 19: writer.WriterService.SaveOperationDuration:input_type -> writer.CreateOperDurRequest
	31, // 20: writer.WriterService.GetOperationDurations:input_type -> google.protobuf.Empty
	20, // 21: writer.WriterService.SkipAgentSubExpressions:input_type -> writer.SkipAgentSubExpressionsRequest
	27, // 22: writer.WriterService.CreateUser:input_type -> writer.CreateUserRequest
	29, // 23: writer.WriterService.GetUserByCred:input_type -> writer.GetUserByCredRequest
	22, // 24: writer.WriterService.CreateToken:input_type -> writer.CreateTokenRequest
	24, // 25: writer.WriterService.GetToken:input_type -> writer.GetTokenRequest
	31, // 26: writer.WriterService.Heartbeat:output_type -> google.protobuf.Empty
	4,  // 27: writer.WriterService.StartEval:output_type -> writer.StartEvalResponse
	31, // 28: writer.WriterService.StopEval:output_type -> google.protobuf.Empty
	7,  // 29: writer.WriterService.GetReadySubExpressions:output_type -> writer.ReadySubExpressionsResponse
	0,  // 30: writer.WriterService.GetExpressionByReqUid:output_type -> writer.Expression
	10, // 31: writer.WriterService.CreateExpression:output_type -> writer.CreateExpressionResponse
	12, // 32: writer.WriterService.CreateSubExpression:output_type -> writer.CreateSubExpressionResponse
	14, // 33: writer.WriterService.GetExpressions:output_type -> writer.GetExpressionsResponse
	16, // 34: writer.WriterService.GetAgents:output_type -> writer.GetAgentsResponse
	31, // 35: writer.WriterService.SaveOperationDuration:output_type -> google.protobuf.Empty
	19, // 36: writer.WriterService.GetOperationDurations:output_type -> writer.GetOperDurResponse
	31, // 37: writer.WriterService.SkipAgentSubExpressions:output_type -> google.protobuf.Empty
	28, // 38: writer.WriterService.CreateUser:output_type -> writer.CreateUserResponse
	30, // 39: writer.WriterService.GetUserByCred:output_type -> writer.GetUserByCredResponse
	23, // 40: writer.WriterService.CreateToken:output_type -> writer.CreateTokenResponse
	25, // 41: writer.WriterService.GetToken:output_type -> writer.GetTokenResponse
	26, // [26:42] is the sub-list for method output_type
	10, // [10:26] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_init() }
func file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_init() {
	if File_dbagent_internal_api_grpcservice_writergrpc_writer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubExpression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEvalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartEvalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopEvalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadySubExpressionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadySubExpressionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpressionByReqUidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExpressionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExpressionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubExpressionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSubExpressionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExpressionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetExpressionsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Agent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OperationDuration); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOperDurRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOperDurResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkipAgentSubExpressionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByCredRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByCredResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_goTypes,
		DependencyIndexes: file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_depIdxs,
		MessageInfos:      file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_msgTypes,
	}.Build()
	File_dbagent_internal_api_grpcservice_writergrpc_writer_proto = out.File
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_rawDesc = nil
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_goTypes = nil
	file_dbagent_internal_api_grpcservice_writergrpc_writer_proto_depIdxs = nil
}
